ThePlaceToMeet/Models/Domain/Reservatie.cs
using System;

namespace ThePlaceToMeet.Models.Domain
{
    public class Reservatie
    {
        public int Id { get; set; }
        public int AantalPersonen { get; set; }
        public DateTime Dag { get; set; }
        public int BeginUur { get; set; }
        public int DuurInUren { get; set; }
        public int Tot => BeginUur + DuurInUren;
        public decimal PrijsPerUur { get;  set; } //prijs voor huur vergaderruimte per uur op het moment van de reservatie, nog zonder de korting
        public decimal PrijsPerPersoonStandaardCatering { get;  set; } //prijs voor de standaardcatering (koffie, thee, water) per persoon op het moment van de reservatie. 0 als geen standaardcatering wordt aangevraagd
        public decimal PrijsPerPersoonCatering { get; set; } //prijs voor de catering per persoon op het moment van de reservatie, indien voorzien, anders 0. 
        public Catering Catering { get; set; }
        public Korting Korting { get; set; }
        public decimal TotalePrijs =>
          PrijsPerUur * DuurInUren * (1 - (Korting != null ? (decimal)Korting.Percentage / 100 : 0)) + ((PrijsPerPersoonStandaardCatering + PrijsPerPersoonCatering) * AantalPersonen);

    }
}

ThePlaceToMeet/Models/ReservatieViewModels/ReservatieViewModel.cs
using System;
using ThePlaceToMeet.Models.Domain;
using System.ComponentModel.DataAnnotations;

namespace ThePlaceToMeet.Controllers
{
    public class ReservatieViewModel
    {
        public int VergaderruimteId { get; set; }

        public string Naam { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime Dag { get; set; }

        [Required]
        [Range(8, 20)]
        [Display(Name = "Begin uur")]
        public int BeginUur { get; set; }

        [Required]
        [Display(Name = "Hoeveel uur wil je de vergaderzaal reserveren?")]
        public int Duur { get; set; }



        [Required]
        [Display(Name = "Met hoeveel personen wil je vergaderen?")]
        public int AantalPersonen { get; set; }

        [Display(Name = "Standaard catering (koffie, thee, water) ")]
        public bool StandaardCatering { get; set; }

        [Display(Name = "Indien je ook catering wenst, selecteer wat nodig is")]
        public int CateringId { get; set; }

        public ReservatieViewModel()
        {
            Dag = DateTime.Today.Date.AddDays(7);
            BeginUur = 8;
            Duur = 2;
            AantalPersonen = 1;
        }

        public ReservatieViewModel(Vergaderruimte ruimte) : this()
        {
            Naam = ruimte.Naam;
        }
    }
}

ThePlaceToMeet/Controllers/ReservatieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ThePlaceToMeet.Filters;
using ThePlaceToMeet.Models.Domain;

namespace ThePlaceToMeet.Controllers
{
    public class ReservatieController : Controller
    {
        private readonly IVergaderruimteRepository _vergaderruimteRepository;
        private readonly ICateringRepository _cateringRepository;
        private readonly IKortingRepository _kortingRepository;

        public ReservatieController(IVergaderruimteRepository vergaderruimteRepository, ICateringRepository cateringRepository, IKortingRepository kortingRepository)
        {
            _vergaderruimteRepository = vergaderruimteRepository;
            _cateringRepository = cateringRepository;
            _kortingRepository = kortingRepository;
        }

        public IActionResult Index(int? aantalPersonen)
        {
            // implementeer
            IEnumerable<Vergaderruimte> ruimtes;
            if (aantalPersonen.HasValue)
                ruimtes = _vergaderruimteRepository.GetByMaxAantalPersonen(aantalPersonen.Value);
            else
                ruimtes = _vergaderruimteRepository.GetAll();
            ViewData["aantalPersonen"] = aantalPersonen;
            return View(ruimtes.OrderBy(v => v.VergaderruimteType).ThenBy(v => v.MaximumAantalPersonen));

        }

        [Authorize(Policy = "Klant")]
        public IActionResult Reserveer(int id)
        {
            Vergaderruimte ruimte = _vergaderruimteRepository.GetById(id);
            if (ruimte == null)
                return NotFound();
            ViewData["catering"] = new SelectList(_cateringRepository.GetAll().OrderBy(c => c.Titel), nameof(Catering.Id), nameof(Catering.Titel));
            return View(new ReservatieViewModel(ruimte));
        }

        [HttpPost]
        [Authorize(Policy = "Klant")]
        [ServiceFilter(typeof(KlantFilter))]
        public IActionResult Reserveer(int id, ReservatieViewModel viewmodel, Klant klant)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    Catering catering = viewmodel.CateringId != 0 ? _cateringRepository.GetBy(viewmodel.CateringId) : null;
                    Vergaderruimte ruimte = _vergaderruimteRepository.GetById(id);
                    Reservatie reservatie = ruimte.Reserveer(klant, _kortingRepository.GetAll(), viewmodel.Dag, viewmodel.BeginUur, viewmodel.Duur, viewmodel.AantalPersonen, catering, viewmodel.StandaardCatering);
                    _vergaderruimteRepository.SaveChanges();
                    return View("Bevestiging", reservatie);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            ViewData["catering"] = new SelectList(_cateringRepository.GetAll().OrderBy(c => c.Titel), nameof(Catering.Id), nameof(Catering.Titel));
            return View(viewmodel);

        }
    }
}

ThePlaceToMeet/Views/Reservatie/Bevestiging.cshtml
@model ThePlaceToMeet.Models.Domain.Reservatie

@{
    ViewData["Title"] = "Bevestiging";
}

<h2>Bevestiging reservatie</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Dag
        </dt>
        <dd>
            @Model.Dag.ToShortDateString()
        </dd>
        <dt>
            Van
        </dt>
        <dd>
            @Model.BeginUur u
        </dd>
        <dt>
            Tot
        </dt>
        <dd>
            @Model.Tot u
        </dd>
        <dt>
            Aantal personen
        </dt>
        <dd>
            @Model.AantalPersonen
        </dd>
        <dt>
            Prijs voor de ruimte per u
        </dt>
        <dd>
            @($"{Model.PrijsPerUur:N2} €")
        </dd>
        <dt>
            Prijs per persoon voor de standaard catering
        </dt>

        @if (Model.PrijsPerPersoonStandaardCatering != 0)
        {
            <dd>
                @($"{Model.PrijsPerPersoonStandaardCatering:N2} €")
            </dd>
        }
        else
        {
            <dd>niet voorzien</dd>
        }

        @if (Model.Catering != null)
        {
            <dt>
                Prijs per persoon voor @Model.Catering.Titel
            </dt>
            <dd>
                @($"{Model.PrijsPerPersoonCatering:N2} €")
            </dd>
        }
        <dt>
            Percentage korting
        </dt>
        <dd>
            @(Model.Korting != null ? $"{Model.Korting.Percentage} %" : "")
        </dd>
        <dt>
            Totale prijs
        </dt>
        <dd>
            @($"{Model.TotalePrijs:N2} €")
        </dd>
    </dl>
</div>
<div>

    <a asp-action="Index">Terug naar overzicht</a>
</div>

ThePlaceToMeet/Views/Reservatie/Index.cshtml
@model IEnumerable<Vergaderruimte>
@{
    ViewData["Title"] = "Index";
}

<h2>Reserveer een vergaderruimte</h2>
<div id="zoek">
    <div class="col-md-12">
        <form>
            <div class="form-group">
                <label for="aantalPersonen" class="control-label">Zoek een vergaderruimte voor </label>
                <input type="number" name="aantalPersonen" id="aantalPersonen" placeholder="aantal" value=@ViewData["aantalPersonen"] style="border:1px solid #dedede" /> <b>personen</b>&nbsp;&nbsp;
                <input type="submit" value="zoek" class="btn btn-default" />
            </div>
        </form>
        @if (Model.Count() == 0)
        {
            <p>Geen vergaderruimtes gevonden</p>
        }
        else
        {
            @foreach (var item in Model)
            {

                <div class="col-md-4">
                    <p class="text-center"><strong>@item.Naam</strong></p>
                    <p class="text-center small">Maximaal @item.MaximumAantalPersonen personen</p>
                    <img src="~/images/@(item.VergaderruimteType.ToString()).jpg" alt="meetingroom" class="room" />
                    <div class="text-center btn-reserveer"><a class="btn btn-default" asp-controller="Reservatie" asp-action="Reserveer" asp-route-id="@item.Id">Reserveer</a></div>
                </div>
            }
        }

    </div>
    </div>

ThePlaceToMeet/Views/Reservatie/Reserveer.cshtml
@model ThePlaceToMeet.Controllers.ReservatieViewModel

@{
    ViewData["Title"] = "Reserveer";
}

<h2>Reserveer @Model.Naam</h2>

<hr />
<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Dag" class="control-label"></label>
                <input asp-for="Dag" class="form-control" />
                <span asp-validation-for="Dag" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BeginUur" class="control-label"></label>
                <input asp-for="BeginUur" class="form-control"/>
                <span asp-validation-for="BeginUur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duur" class="control-label"></label>
                <input asp-for="Duur" class="form-control"/>
                <span asp-validation-for="Duur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AantalPersonen" class="control-label"></label>
                <input asp-for="AantalPersonen" class="form-control"/>
                <span asp-validation-for="AantalPersonen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="StandaardCatering" /> @Html.DisplayNameFor(model => model.StandaardCatering)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="CateringId" class="control-label"></label>
                <!-- Implementeer de selectlist-->

                <select asp-for="CateringId" asp-items=@(ViewData["catering"] as SelectList) class="form-control">
                    <option value="0">--selecteer catering--</option>
                </select>

                <span asp-validation-for="CateringId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-default">Reserveer</button>
                <a asp-action="Index">Terug naar overzicht</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}